### PR TITLE
upgraded Go version and dependencies

### PR DESCRIPTION
**Pull request by mirshahriar**
#### Summary
Upgraded Go version and dependencies

#### Ticket Link
[MM-48114](https://mattermost.atlassian.net/browse/MM-48114)

#### Release Note

```release-note
Upgraded Go version to 1.19
```

### CODE REVIEW

**Review by fmartingr — APPROVED** [review]
LGTM! Thanks for adding more QoL here as well.

~~Just wondering, any reason to vendor the dependencies? Not that I'm complaining, just wondering if we're going to do it, replicate it across other projects as well.~~ Disregard this comment and related conversation.

**Comment by mirshahriar** [comment]
> LGTM! Thanks for adding more QoL here as well.
> 
> Just wondering, any reason to vendor the dependencies? Not that I'm complaining, just wondering if we're going to do it, replicate it across other projects as well.

I have updated a few dependencies here and I believe it is recommended to have a consistent state in the vendor folder with mod files. We can add the vendor folder to gitignore to match what other projects have done here.

**Comment by fmartingr** [comment]
> > LGTM! Thanks for adding more QoL here as well.
> > Just wondering, any reason to vendor the dependencies? Not that I'm complaining, just wondering if we're going to do it, replicate it across other projects as well.
> 
> I have updated a few dependencies here and I believe it is recommended to have a consistent state in the vendor folder with mod files. We can add the vendor folder to gitignore to match what other projects have done here.

I'm ok with vendoring, just wondering if you did it for some reason. I would gladly do it across all projects so we don't get [left-padded](https://arstechnica.com/information-technology/2016/03/rage-quit-coder-unpublished-17-lines-of-javascript-and-broke-the-internet/). 😬

**Comment by mirshahriar** [comment]
> > > LGTM! Thanks for adding more QoL here as well.
> > > Just wondering, any reason to vendor the dependencies? Not that I'm complaining, just wondering if we're going to do it, replicate it across other projects as well.
> > 
> > 
> > I have updated a few dependencies here and I believe it is recommended to have a consistent state in the vendor folder with mod files. We can add the vendor folder to gitignore to match what other projects have done here.
> 
> I'm ok with vendoring, just wondering if you did it for some reason. I would gladly do it across all projects so we don't get [left-padded](https://arstechnica.com/information-technology/2016/03/rage-quit-coder-unpublished-17-lines-of-javascript-and-broke-the-internet/). 😬

I can't think of a specific reason why I do vendor. However, I always keep my vendor folder up-to-date. I believe it is a matter of choice. Take a look at this: https://stackoverflow.com/a/61547800

**Pull request merged**
