### PR TITLE
[GH-223] Add Image Pull Secrets

### PR DESCRIPTION
**Pull request by mjnagel**
#### Summary
This PR exposes image pull secrets as an option in the Mattermost spec.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-operator/issues/223

#### Release Note
```release-note
Exposed `imagePullSecrets` in the Mattermosts spec
```

### CODE REVIEW

**Review by gabrieljackson — APPROVED** [review]
LGTM! Thanks for the contribution.

**Review by Szymongib — APPROVED** [review]
Thanks for adding this @mjnagel!

**Comment by mjnagel** [comment]
@Szymongib just out of curiosity so I know when to expect this - how does your tagging process work/when are new releases/tags cut?

**Comment by Szymongib** [comment]
@mjnagel We do not have any particular schedule for releases and do them whenever there are some features we want to roll out so it is hard for me to say when the next release will be out.

We usually cut release from master unless we want to just cherry-pick some bug fixes.

**Pull request merged**
