### PR TITLE
Mm 17050 - BlueGreen controller and API 

### PR DESCRIPTION
**Pull request by stylianosrigas**
Tickets:
- https://mattermost.atlassian.net/browse/MM-17050
- https://mattermost.atlassian.net/browse/MM-17077

This PR introduces the BlueGreen controller and API in the Mattermost Operator.

### CODE REVIEW

**Comment by gabrieljackson** [comment]
Hmm, looks like we may have some build and test issues to work out here.

**Comment by jwilander** [comment]
For some reason there's a slight difference between `make generate` locally and on CI. @stylianosrigas and I spent some time looking at it but haven't figured it out yet

**Comment by cpanato** [comment]
fixed, the issue was for some reason it was using the operator-sdk v0.8.0 and not v0.9.0 added the clean step to remove the operator-sdk binary

**Comment by cpanato** [comment]
the real issue was the operator-sdk binary was committed and that binary was the version 0.8.0. removed now and add in the gitignore

**Comment by jwilander** [comment]
@stylianosrigas we're closing this right per our chat?

**Comment by stylianosrigas** [comment]
@jwilander Yeap closing now ;)

**Pull request closed without merging**
