### PR TITLE
[MM-29303] add release script

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Add release script to help in the release cut

now, you need to run `./scripts/release.sh --tag=1.3.4`  and it will:

- bump the version in `version/version.go`
- update the image in `docs/mattermost-operator/mattermost-operator.yaml`
- commit and push to upstream
- tag and push to upstream

#### Ticket Link
Jira:
- https://mattermost.atlassian.net/browse/MM-29303
- https://mattermost.atlassian.net/browse/MM-29601

#### Release Note

```release-note
add release script
```

### CODE REVIEW

**Review by stylianosrigas — APPROVED** [review]
Nice one @cpanato . Can you add some lines in the Readme to include this step for a release?

**Comment by cpanato** [comment]
@stylianosrigas done

**Review by gabrieljackson — APPROVED** [review]
Awesome!

**Pull request merged**
