### PR TITLE
feat(mattermost): add additional volumes and volumeMounts in mattermost deployment

### PR DESCRIPTION
**Pull request by agill17**
So that users can mount custom CA

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by cpanato** [comment]
@agill17 please run `make generate`

**Comment by agill17** [comment]
> @agill17 please run `make generate` and commit the changes as well

Done 👍

**Comment by gabrieljackson** [comment]
Thanks for this @agill17! It looks like there is still an issue with the generate check showing a mismatch in the expected generated files.

When you get a second, could you ensure you merge master and run `make generate` again? Thank you.

**Comment by Szymongib** [comment]
Sorry for the late response. I think you also need to run `make manifests` as there were changes to CRs.

**Comment by agill17** [comment]
> Sorry for the late response. I think you also need to run `make manifests` as there were changes to CRs.

Done 👍

**Comment by agill17** [comment]
Looks like the CI failures are likely related to different local versions of libraries/generators I have locally.

**Comment by Szymongib** [comment]
The CRDs are generated by `controller-gen` you might want to check if it is in version `v0.4.0`.

**Comment by jfrerich** [comment]
Hi @agill17, could you check out the comment from @Szymongib and see if that resolves your CI issues?  Thanks!

**Comment by jfrerich** [comment]
@Szymongib or @gabrieljackson, is the CI issue something that one of you could fix and push to the PR to get it across the finish line? Thanks!

**Comment by gabrieljackson** [comment]
@agill17, did you have any luck trying Szymon's `controller-gen` version check?

Let us know if you would like to take over the PR from here to get it merged in.

**Comment by gabrieljackson** [comment]
@agill17, we wanted to thank you for your work on this PR and to let you know that we definitely wanted this available going forward in our operator. Due to this, we ensured that it is now part of our new Beta CR and is available for use:

https://github.com/mattermost/mattermost-operator/blob/master/apis/mattermost/v1beta1/mattermost_types.go#L65-L71

If you have any questions then please reach out. We will close this PR, but wanted to thank you again for your work on the operator.

**Pull request closed without merging**
